"""
Mapping of Nigerian stock symbols to their sectors.
This is a pre-defined mapping to avoid making individual API calls.
"""

NIGERIAN_STOCK_SECTORS = {
    # Banking & Financial Services
    'ACCESS': 'Banking',
    'ACCESSCORP': 'Banking',
    'FBNH': 'Banking',
    'FCMB': 'Banking',
    'FIDELITYBK': 'Banking',
    'GTCO': 'Banking',
    'STANBIC': 'Banking',
    'UBA': 'Banking',
    'UBN': 'Banking',
    'WEMABANK': 'Banking',
    'ZENITHBANK': 'Banking',
    'AIICO': 'Banking',
    'AFRIPRUD': 'Banking',
    'CORNERST': 'Banking',
    'LASACO': 'Banking',
    'LINKASSURE': 'Banking',
    'MANSARD': 'Banking',
    'NEM': 'Banking',
    'PRESTIGE': 'Banking',
    'ROYALEX': 'Banking',
    'STACO': 'Banking',
    'WAPIC': 'Banking',
    'ABBEYBDS': 'Banking',
    'ASOSAVINGS': 'Banking',
    'INFINITY': 'Banking',
    'LIVINGTRUST': 'Banking',
    'NPFMCRFBK': 'Banking',
    'UNITYBNK': 'Banking',
    'CUSTODIAN': 'Banking',
    'DEAPCAP': 'Banking',
    'VFDGROUP': 'Banking',
    'UCAP': 'Banking',
    'CILEASING': 'Banking',
    'ETI': 'Banking',
    'FIRSTHOLDCO': 'Banking',
    'STERLINGNG': 'Banking',
    
    # Consumer Goods
    'DANGCEM': 'Consumer Goods',
    'BUA': 'Consumer Goods',
    'BUACEMENT': 'Consumer Goods',
    'BUAFOODS': 'Consumer Goods',
    'CADBURY': 'Consumer Goods',
    'DANGSUGAR': 'Consumer Goods',
    'FLOURMILL': 'Consumer Goods',
    'GUINNESS': 'Consumer Goods',
    'HONYFLOUR': 'Consumer Goods',
    'INTBREW': 'Consumer Goods',
    'NESTLE': 'Consumer Goods',
    'NB': 'Consumer Goods',
    'PZ': 'Consumer Goods',
    'UNILEVER': 'Consumer Goods',
    'VITAFOAM': 'Consumer Goods',
    'BERGER': 'Consumer Goods',
    'CHAMPION': 'Consumer Goods',
    'GOLDBREW': 'Consumer Goods',
    'NASCON': 'Consumer Goods',
    'TANTALIZER': 'Consumer Goods',
    
    # Technology & Telecoms
    'AIRTELAFRI': 'Technology',
    'MTNN': 'Technology',
    'CHAMS': 'Technology',
    'COURTVILLE': 'Technology',
    'E-TRANZACT': 'Technology',
    'NCR': 'Technology',
    'CWG': 'Technology',
    'DAARCOMM': 'Technology',
    'LEGENDINT': 'Technology',
    'NSLTECH': 'Technology',
    'OMATEK': 'Technology',
    'TIP': 'Technology',
    
    # Energy
    'OANDO': 'Energy',
    'SEPLAT': 'Energy',
    'TOTAL': 'Energy',
    'CONOIL': 'Energy',
    'ETERNA': 'Energy',
    'MRS': 'Energy',
    'GEREGU': 'Energy',
    'TRANSPOWER': 'Energy',
    'EKOCORP': 'Energy',
    'EUNISELL': 'Energy',
    'MULTIVERSE': 'Energy',
    
    # Industrial
    'BETAGLAS': 'Industrial',
    'CAP': 'Industrial',
    'CUTIX': 'Industrial',
    'GLAXOSMITH': 'Industrial',
    'MAYBAKER': 'Industrial',
    'NEIMETH': 'Industrial',
    'PHARMDEKO': 'Industrial',
    'ACADEMY': 'Industrial',
    'ALEX': 'Industrial',
    'ARADEL': 'Industrial',
    'AUSTINLAZ': 'Industrial',
    'BAPLC': 'Industrial',
    'CHELLARAM': 'Industrial',
    'DUNLOP': 'Industrial',
    'ENAMELWA': 'Industrial',
    'FIDSON': 'Industrial',
    'IMG': 'Industrial',
    'MCNICHOLS': 'Industrial',
    'MECURE': 'Industrial',
    'MORISON': 'Industrial',
    'NOTORE': 'Industrial',
    'PREMPAINTS': 'Industrial',
    'RONCHESS': 'Industrial',
    'RTBRISCOE': 'Industrial',
    'SCOA': 'Industrial',
    'SMURFIT': 'Industrial',
    'THOMASWY': 'Industrial',
    'TRIPPLEG': 'Industrial',
    'UACN': 'Industrial',
    'UNIONDICON': 'Industrial',
    'UPL': 'Industrial',
    'VANLEER': 'Industrial',
    'HMCALL': 'Industrial',
    
    # Agriculture
    'OKOMUOIL': 'Agriculture',
    'PRESCO': 'Agriculture',
    'ELLAHLAKES': 'Agriculture',
    'FTNCOCOA': 'Agriculture',
    
    # Real Estate
    'UPDC': 'Real Estate',
    'UPDCREIT': 'Real Estate',
    'SFSREIT': 'Real Estate',
    'UHOMREIT': 'Real Estate',
    
    # Transportation
    'NAHCO': 'Transportation',
    'SAHCO': 'Transportation',
    'ABCTRANS': 'Transportation',
    'CAVERTON': 'Transportation',
    'JAPAULGOLD': 'Transportation',
    'TRANSEXPR': 'Transportation',
    
    # Utilities
    'IKEJAHOTEL': 'Utilities',
    'JAIZBANK': 'Utilities',
    'JULI': 'Utilities',
    'LEARNAFRCA': 'Utilities',
    'LIVESTOCK': 'Utilities',
    'MULTITREX': 'Utilities',
    'NNFM': 'Utilities',
    'REDSTAREX': 'Utilities',
    'ROYALEX': 'Utilities',
    'SKYAVN': 'Utilities',
    'THOMASWY': 'Utilities',
    'TRANSCOHOT': 'Utilities',
    'VERITASKAP': 'Utilities',
    'WAPCO': 'Utilities',
    
    # Investment & Securities
    'MERGROWTH': 'Investment',
    'MERVALUE': 'Investment',
    'NEWGOLD': 'Investment',
    'NIDF': 'Investment',
    'AVAIF': 'Investment',
    
    # Media & Entertainment
    'AFROMEDIA': 'Media',
    'MEYER': 'Media',
    
    # Conglomerates
    'TRANSCORP': 'Conglomerate',
    'JBERGER': 'Conglomerate',
    'JOHNHOLT': 'Conglomerate',
    
    # Exchange & Trading
    'NGXGROUP': 'Exchange',
    
    # Insurance
    'AFRINSURE': 'Insurance',
    'CONHALLPLC': 'Insurance',
    'FTGINSURE': 'Insurance',
    'GUINEAINS': 'Insurance',
    'INTENEGINS': 'Insurance',
    'MBENEFIT': 'Insurance',
    'REGALINS': 'Insurance',
    'SOVRENINS': 'Insurance',
    'STDINSURE': 'Insurance',
    'SUNUASSUR': 'Insurance',
    'UNIVINSURE': 'Insurance',
} 